name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-windows-amd64.zip -OutFile cloudflared.zip
    - run: Expand-Archive cloudflared.zip
    
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.PASSWORD }}" -Force)
    - run: Set-WinUserLanguageList -LanguageList tr, en-US -Force
         
    - run:  Remove-Item -Path cloudflared.ps1 -Force -ErrorAction SilentlyContinue
    - name: cloudflared-Without Login
      run:  Invoke-WebRequest https://raw.githubusercontent.com/dikeckaan/Windows-RDP-ACTIONS/main/cloudflared.ps1 -OutFile cloudflared.ps1
    - run: .\cloudflared.ps1 ${{ secrets.TG_TOKEN }} ${{ secrets.TG_CHAT_ID }}
    
